-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 17:03:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema eachteach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eachteach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eachteach` DEFAULT CHARACTER SET latin1 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`profile_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`profile_image` (
  `profile_id` INT(11) NOT NULL,
  `client_id` INT(11) NOT NULL,
  `profile_image_location` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`profile_id`),
  UNIQUE INDEX `client_id` (`client_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `database`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`clients` (
  `id` INT(11) NOT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `rating` INT(11) NULL DEFAULT NULL,
  `tokens` INT(11) NULL DEFAULT NULL,
  `high_school` VARCHAR(255) NULL DEFAULT NULL,
  `tertiary_school` VARCHAR(255) NULL DEFAULT NULL,
  `institution` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `degree` VARCHAR(255) NULL DEFAULT NULL,
  `occupation` VARCHAR(255) NULL DEFAULT NULL,
  `profile_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `profile_id` (`profile_id` ASC),
  CONSTRAINT `clients_ibfk_1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `database`.`profile_image` (`profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `eachteach` ;

-- -----------------------------------------------------
-- Table `eachteach`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`topics` (
  `topic_id` INT(11) NOT NULL AUTO_INCREMENT,
  `topic_description` VARCHAR(255) NULL DEFAULT NULL,
  `topic_field` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`topic_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`appointments` (
  `appointment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `appointment_date` DATETIME NULL DEFAULT NULL,
  `topic_id` INT(11) NULL DEFAULT NULL,
  `appointment_location` VARCHAR(255) NULL DEFAULT NULL,
  `appointment_time` DATETIME NULL DEFAULT NULL,
  `appointment_title` VARCHAR(255) NULL DEFAULT NULL,
  `appointment_status` CHAR(1) NULL DEFAULT NULL,
  `appointment_duration` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`appointment_id`),
  INDEX `topic_id` (`topic_id` ASC),
  CONSTRAINT `appointments_ibfk_1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `eachteach`.`topics` (`topic_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`clients` (
  `client_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_lastname` VARCHAR(255) NULL DEFAULT NULL,
  `client_firstname` VARCHAR(255) NULL DEFAULT NULL,
  `client_email` VARCHAR(255) NULL DEFAULT NULL,
  `client_password` VARCHAR(255) NULL DEFAULT NULL,
  `client_security_q1` VARCHAR(255) NULL DEFAULT NULL,
  `client_security_q2` VARCHAR(255) NULL DEFAULT NULL,
  `client_security_a1` VARCHAR(255) NULL DEFAULT NULL,
  `client_security_a2` VARCHAR(255) NULL DEFAULT NULL,
  `client_rating` INT(11) NULL DEFAULT NULL,
  `client_tokens` INT(11) NULL DEFAULT NULL,
  `client_high_school` VARCHAR(255) NULL DEFAULT NULL,
  `client_tertiary_school` VARCHAR(255) NULL DEFAULT NULL,
  `client_institution` VARCHAR(255) NULL DEFAULT NULL,
  `client_location` VARCHAR(255) NULL DEFAULT NULL,
  `client_degree` VARCHAR(255) NULL DEFAULT NULL,
  `client_occupation` VARCHAR(255) NULL DEFAULT NULL,
  `client_cell_no` VARCHAR(255) NULL DEFAULT NULL,
  `profile_img` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`client_appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`client_appointments` (
  `client_id` INT(11) NULL DEFAULT NULL,
  `appointment_id` INT(11) NULL DEFAULT NULL,
  INDEX `client_id` (`client_id` ASC),
  INDEX `appointment_id` (`appointment_id` ASC),
  CONSTRAINT `client_appointments_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `eachteach`.`clients` (`client_id`),
  CONSTRAINT `client_appointments_ibfk_2`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `eachteach`.`appointments` (`appointment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`client_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`client_topics` (
  `client_id` INT(11) NULL DEFAULT NULL,
  `topic_id` INT(11) NULL DEFAULT NULL,
  INDEX `client_id` (`client_id` ASC),
  INDEX `topic_id` (`topic_id` ASC),
  CONSTRAINT `client_topics_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `eachteach`.`clients` (`client_id`),
  CONSTRAINT `client_topics_ibfk_2`
    FOREIGN KEY (`topic_id`)
    REFERENCES `eachteach`.`topics` (`topic_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`connections` (
  `connection_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NOT NULL,
  `connected_with` INT(11) NOT NULL,
  `connection_type` VARCHAR(255) NULL DEFAULT NULL,
  `Date_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`connection_id`),
  INDEX `client_id` (`client_id` ASC),
  CONSTRAINT `connections_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `eachteach`.`clients` (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`forums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`forums` (
  `forum_message_id` INT(11) NOT NULL AUTO_INCREMENT,
  `forum_message` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`forum_message_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`discussion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`discussion` (
  `post_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NULL DEFAULT NULL,
  `post_title` VARCHAR(255) NULL DEFAULT NULL,
  `post_date_time` DATETIME NULL DEFAULT NULL,
  `message_id` INT(11) NULL DEFAULT NULL,
  `post_parent` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `client_id` (`client_id` ASC),
  INDEX `message_id` (`message_id` ASC),
  CONSTRAINT `discussion_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `eachteach`.`clients` (`client_id`),
  CONSTRAINT `discussion_ibfk_2`
    FOREIGN KEY (`message_id`)
    REFERENCES `eachteach`.`forums` (`forum_message_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`fcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`fcategory` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `detail` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `datetime` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`fquestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`fquestions` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `categoryid` INT(11) NOT NULL,
  `topic` VARCHAR(255) NOT NULL DEFAULT '',
  `detail` LONGTEXT NOT NULL,
  `name` VARCHAR(65) NOT NULL DEFAULT '',
  `email` VARCHAR(65) NOT NULL DEFAULT '',
  `datetime` VARCHAR(25) NOT NULL DEFAULT '',
  `view` INT(4) NOT NULL DEFAULT '0',
  `reply` INT(4) NOT NULL DEFAULT '0',
  `fcategory_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fquestions_fcategory1_idx` (`fcategory_id` ASC),
  CONSTRAINT `fk_fquestions_fcategory1`
    FOREIGN KEY (`fcategory_id`)
    REFERENCES `eachteach`.`fcategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`fanswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`fanswer` (
  `question_id` INT(4) NOT NULL DEFAULT '0',
  `a_id` INT(4) NOT NULL DEFAULT '0',
  `a_name` VARCHAR(65) NOT NULL DEFAULT '',
  `a_answer` LONGTEXT NOT NULL,
  `a_datetime` VARCHAR(25) NOT NULL DEFAULT '',
  `fquestions_id` INT(4) NOT NULL,
  INDEX `a_id` (`a_id` ASC),
  INDEX `fk_fanswer_fquestions1_idx` (`fquestions_id` ASC),
  CONSTRAINT `fk_fanswer_fquestions1`
    FOREIGN KEY (`fquestions_id`)
    REFERENCES `eachteach`.`fquestions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`fcomment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`fcomment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `postid` INT(11) NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `datetime` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(100) NOT NULL,
  `image_text` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `msg` TEXT NOT NULL,
  `to` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`reply` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `postid` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `reply` VARCHAR(255) NOT NULL,
  `datetime` VARCHAR(255) NOT NULL,
  `fcomment_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reply_fcomment1_idx` (`fcomment_id` ASC),
  CONSTRAINT `fk_reply_fcomment1`
    FOREIGN KEY (`fcomment_id`)
    REFERENCES `eachteach`.`fcomment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eachteach`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eachteach`.`reviews` (
  `review_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NULL DEFAULT NULL,
  `review_poster_id` INT(11) NULL DEFAULT NULL,
  `review_poster_name` VARCHAR(100) NULL DEFAULT NULL,
  `Message` VARCHAR(250) NULL DEFAULT NULL,
  `review_date_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `client_id` (`client_id` ASC),
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `eachteach`.`clients` (`client_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
